version: "3"
services:
  database:
    container_name: database
    image: postgres:16.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "herio"
      POSTGRES_PASSWORD: "heriopass"
      POSTGRES_DB: "herio"

  cf-server:
    image: adobecoldfusion/coldfusion:latest
    ports:
      - "8500:8500"
    volumes:
      - ./app:/app
    environment:
      - acceptEULA=YES
      - password=password
